name = "dubmate-room-registry"
main = "src/index.ts"
compatibility_date = "2025-02-04"

[[kv_namespaces]]
binding = "ROOMS"
id = "e954cacd7b034f8ca646c2142034614b"

[[routes]]
pattern = "dubmate.bkaproductions.com"
custom_domain = true
